// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA1MwvmY0ylcAnivpYpeMQi9mcGIPPGQ90',
    appId: '1:1017104351180:android:01808c7eac7f03c6f1a769',
    messagingSenderId: '1017104351180',
    projectId: 'uber-lite777',
    databaseURL: 'https://uber-lite777-default-rtdb.firebaseio.com',
    storageBucket: 'uber-lite777.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDe12DM2PJuclUHm7qDUEAy6EItDPKOHuk',
    appId: '1:1017104351180:ios:fb6531584fbb5c7ef1a769',
    messagingSenderId: '1017104351180',
    projectId: 'uber-lite777',
    databaseURL: 'https://uber-lite777-default-rtdb.firebaseio.com',
    storageBucket: 'uber-lite777.appspot.com',
    iosClientId: '1017104351180-j7ilenj09hp2pq9g5jdvtupsuqom8nnc.apps.googleusercontent.com',
    iosBundleId: 'com.sateeshjh.uberLiteDriver',
  );
}
